import { useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import useAuth from 'hooks/useAuth'
import { Github, Loading } from 'components/icons'
import styles from 'styles/Home.module.css'

import { logInGithub } from 'firebase/client'

export default function Home () {
  const { initialized, user } = useAuth()
  const router = useRouter()

  useEffect(() => {
    user && router.replace('/dashboard/home')
  }, [user])

  const handleClick = () => {
    logInGithub().catch((err) => console.log(err))
  }

  return (
    <>
      <Head>
        <title>Utilities X</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>Utilities X</h1>
          {initialized === 'not_logged' && (
            <button
              className={styles.button}
              // backgroundColor="#0d1117"
              // fontSize="2rem"
              // color="#fff"
              onClick={handleClick}
            >
              <Github /> Sign in with Github
            </button>
          )}
          {initialized === 'idle' && <Loading />}
        </div>
      </main>
    </>
  )
}
